require("settings.settings")
require("settings.notational")
require("settings.plugins")
require("settings.colorscheme")
require("settings.treesitter")
require("settings.bufferline")
require("settings.telescope")
require("settings.formatter")
require("settings.cmp")
require("settings.hop")
require("settings.gitsigns")
require("settings.nvim_lsp")
require("settings.nvim_lint")
require("settings.close_tab")
require("settings.blankline")
require("settings.qf_helper")
require("settings.session")
vim.o.mouse = ""
